### ISSUE TITLE
Palavra escrita errada

### ISSUE THREAD

**Issue by pamnovalli** [prefeiturasp/SME-plataforma-curriculo-interface#104]
**Descreva o bug**

Uma descrição clara e precisa do que o bug é.

**Para Reproduzir**
Os passos para reproduzir estão abaixo:
1. Navegue até '.Matriz de Saberes'
2. Clique no 'Resolução de problemas'
4. O erro encontra-se na escrita da palavra desafios

**O que era para acontecer**
A palavra deveria estar escrita desafios mas está sendo visualizada desa!os
**Screenshots**

Se for aplicável, tire prints do erro.

**Desktop (complete com as informações):**
 - Sistema Operacional[e.g. iOS]
 - NAgagor [e.g. chrome, safari]

**Smartphone complete com as informações)::**
 - Aparelho: [e.g. iPhone6]
 - Sistema Operacional: [e.g. iOS8.1]
 - Navegador [e.g. stock browser, safari]

**Algo a mais?**
Adicione informações extras que julgar pertinente.
![captura de tela de 2019-01-22 14-07-02](https://user-images.githubusercontent.com/26384933/51550097-d0c16e80-1e52-11e9-8b9a-bbbffafdcc71.png)

**Comment by eomine** [comment]
@pamnovalli @malungo O texto foi cadastrado c/ erro de digitação no admin:

http://curriculo.jurema.la/api/saberes
